import type { EvaluationQuestion, JevState } from "@/lib/ai";

import { needsScreening } from "./thresholds";
import { MODEL_BUCKETS, type ClassifyContext, type ModelBucket, type ModelResult } from "./types";

export const TEXT_LIMIT = 2000;

export type JevAnswer =
  | { type: "choice"; choice: string; probabilities?: Record<string, number> }
  | { type: "score"; score: number; probabilities?: Record<string, number> }
  | { type: "boolean"; probability: number };

export type JevRequest = {
  state: JevState;
  questions: Record<string, EvaluationQuestion>;
};

const BUCKET_QUESTION = {
  type: "choice",
  instructions:
    "Which bucket does `email` belong in? Apply `rules` when they match. " +
    "`examples` are past threads the user moved by hand; follow them for similar mail.",
  criteria: {
    inbox:
      "Mail the user should see: from people, replies, anything that needs action or attention, " +
      "and urgent service notices such as failed payments or security alerts",
    news: "Newsletters, digests, announcements, promotions and marketing, things to read later",
    paper_trail:
      "Receipts, invoices, order and shipping updates, routine account and transactional notifications",
  },
} as const satisfies EvaluationQuestion;

const URGENCY_QUESTION = {
  type: "score",
  instructions: "How urgent is `email` for the user?",
  criteria: [
    "No action ever needed",
    "Worth reading, no action needed",
    "Needs action eventually",
    "Needs action soon, e.g. a payment failed or a deadline is near",
    "Needs action now, e.g. a security alert or a service about to be cut off",
  ],
} as const satisfies EvaluationQuestion;

const HUMAN_QUESTION = {
  type: "boolean",
  instructions: "Was `email` written personally by a human, not generated by a system or a mailing tool?",
} as const satisfies EvaluationQuestion;

const LEGIT_QUESTION = {
  type: "boolean",
  instructions:
    "`sender` has never emailed the user before. Is this a legitimate sender the user would want to " +
    "hear from, rather than spam, phishing, cold outreach or unsolicited promotion?",
} as const satisfies EvaluationQuestion;

export function buildJevRequest(ctx: ClassifyContext): JevRequest {
  const { thread, sender } = ctx;
  const state: JevState = {
    email: {
      toAccount: thread.accountEmail,
      from: { name: thread.fromName, email: thread.fromEmail, domain: sender.domain },
      subject: thread.subject ?? "",
      text: thread.text.slice(0, TEXT_LIMIT),
      messagesInThread: thread.messageCount,
      headers: {
        hasListUnsubscribe: Boolean(thread.headers.listUnsubscribe),
        precedence: thread.headers.precedence ?? null,
        autoSubmitted: thread.headers.autoSubmitted ?? null,
        isReply: Boolean(thread.headers.inReplyTo),
      },
    },
    sender: {
      screenerDecision: sender.decision,
      threadsFromSender: sender.threadCount,
      accountsSeenOn: sender.accountCount,
      userHasWrittenTo: sender.userHasWrittenTo,
      userStartedThread: sender.userStartedThread,
    },
    rules: ctx.rules.map((r) => (r.structured == null ? { text: r.text } : { text: r.text, structured: r.structured })),
    examples: ctx.exemplars.map((e) => ({
      from: e.senderEmail,
      subject: e.subject,
      classifiedAs: e.fromBucket,
      userMovedTo: e.toBucket,
    })),
  };

  const questions: Record<string, EvaluationQuestion> = {
    bucket: BUCKET_QUESTION,
    urgency: URGENCY_QUESTION,
    humanWritten: HUMAN_QUESTION,
  };
  if (needsScreening(sender)) questions.legitNewSender = LEGIT_QUESTION;

  return { state, questions };
}

function isModelBucket(value: string): value is ModelBucket {
  return (MODEL_BUCKETS as readonly string[]).includes(value);
}

export function parseJevAnswers(answers: Record<string, JevAnswer>): ModelResult {
  const bucket = answers.bucket;
  const urgency = answers.urgency;
  const human = answers.humanWritten;
  const legit = answers.legitNewSender;
  if (bucket?.type !== "choice" || !isModelBucket(bucket.choice)) {
    throw new Error(`Jev returned an invalid bucket answer: ${JSON.stringify(bucket)}`);
  }
  if (urgency?.type !== "score") throw new Error("Jev returned no urgency score");
  if (human?.type !== "boolean") throw new Error("Jev returned no human written answer");

  const probabilities: ModelResult["bucketProbabilities"] = {};
  for (const b of MODEL_BUCKETS) {
    probabilities[b] = bucket.probabilities?.[b] ?? (b === bucket.choice ? 1 : 0);
  }

  return {
    bucket: bucket.choice,
    bucketProbabilities: probabilities,
    // Score is 0-4 over the five levels; stored as 1-5.
    urgency: Math.min(5, Math.max(1, Math.round(urgency.score) + 1)),
    humanWritten: human.probability,
    legitNewSender: legit?.type === "boolean" ? legit.probability : null,
  };
}
